[tool.poetry]
name = "AutoWoE"
version = "1.3.4"
description = "Library for automatic interpretable model building (Whitebox AutoML)"
authors = ["Vakhrushev Anton <btbpanda@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/AILab-MLTools/AutoMLWhitebox"
repository = "https://github.com/AILab-MLTools/AutoMLWhitebox"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Typing :: Typed"
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
numpy = "*"
scipy = "*"
pandas = "*"
scikit-learn = ">=1.0.1"
lightgbm = ">=4.6.0"
sphinx = "*"
sphinx-rtd-theme = "*"
joblib = ">=1.2.0"
pytz = "*"
pytest = "*"
jinja2 = "*"
matplotlib = "*"
pillow = ">=12.3.0"
certifi = ">=2023.7.22"
requests = ">=2.33.0"
urllib3 = ">=2.8.0"
seaborn = ">=0.13.2"
tqdm = "^4.62.3"
StrEnum = "^0.4.7"



[tool.poetry.group.dev.dependencies]
notebook = "^6.4.6"
black = ">=24.10.0"
pre-commit = "2.15.0"
mypy = "^0.910"
tox = "*"
darglint = "^1.8.1"
flake8-docstrings = "^1.6.0"
isort = "5.7.0"
jupyter-contrib-nbextensions = "^0.5.1"
jupyter_nbextensions_configurator = "^0.4.1"
jupyter-core = ">=4.11.2"
lxml = ">=6.1.0"
mistune = ">=3.3.0"
nbconvert = ">=7.17.0"
tornado = ">=6.5.9"
virtualenv = ">=21.7.13"
pyyaml = ">=6.0.2"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
