name: tests_macos

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:

jobs:
  macos-tests:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: install deps for MacOS
        run: brew update && brew install libomp cairo pango gdk-pixbuf libffi

      - name: install with pip
        run: |
          pip install tox==4.23.2
          pip install tox-gh-actions==3.2.0

      - name: test with tox
        run: |
          tox -- -vv
