name: tests_ubuntu

on:
  # # At 20:59 every day (23:59 MSK)
  # schedule:
  #   - cron: 59 20 * * *

  # Manually triggerable in github
  workflow_dispatch:

  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  ubuntu-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.10", "3.11", "3.12"] # "3.9" is tested in CI

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install deps for Ubuntu
        run: sudo apt-get install build-essential libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info

      - name: install tox
        run: |
          python3 -m pip install --upgrade pip
          pip3 install tox==3.28.0
          pip3 install tox-gh-actions==2.12.0

      - name: test with tox
        run: |
          tox
