name: tests_ubuntu

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:

jobs:
  ubuntu-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: install deps for Ubuntu
        run: sudo apt-get install build-essential libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info

      - name: install tox
        run: |
          python3 -m pip install --upgrade pip
          pip3 install tox==4.23.2
          pip3 install tox-gh-actions==3.2.0

      - name: test with tox
        run: |
          tox -- -vv
